# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ChampaignBoard_Z7.xdc

# Block Designs: bd/zynq7010/zynq7010.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010 || ORIG_REF_NAME==zynq7010} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_processing_system7_0_0/zynq7010_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_processing_system7_0_0 || ORIG_REF_NAME==zynq7010_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_proc_sys_reset_0_0/zynq7010_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_proc_sys_reset_0_0 || ORIG_REF_NAME==zynq7010_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_axi_interconnect_1_0/zynq7010_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_axi_interconnect_1_0 || ORIG_REF_NAME==zynq7010_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_xlslice_0_0/zynq7010_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_xlslice_0_0 || ORIG_REF_NAME==zynq7010_xlslice_0_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_audio_shift_1/zynq7010_audio_shift_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_audio_shift_1 || ORIG_REF_NAME==zynq7010_audio_shift_1} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_audio_en_0/zynq7010_audio_en_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_audio_en_0 || ORIG_REF_NAME==zynq7010_audio_en_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_audio_type_0/zynq7010_audio_type_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_audio_type_0 || ORIG_REF_NAME==zynq7010_audio_type_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_axi_interconnect_1_1/zynq7010_axi_interconnect_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_axi_interconnect_1_1 || ORIG_REF_NAME==zynq7010_axi_interconnect_1_1} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_fb_use_alt_0/zynq7010_fb_use_alt_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_fb_use_alt_0 || ORIG_REF_NAME==zynq7010_fb_use_alt_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_fb_use_alt1_0/zynq7010_fb_use_alt1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_fb_use_alt1_0 || ORIG_REF_NAME==zynq7010_fb_use_alt1_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_xlconcat_0_1/zynq7010_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_xlconcat_0_1 || ORIG_REF_NAME==zynq7010_xlconcat_0_1} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_xlconcat_1_0/zynq7010_xlconcat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_xlconcat_1_0 || ORIG_REF_NAME==zynq7010_xlconcat_1_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_fb0_use_alt_0/zynq7010_fb0_use_alt_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_fb0_use_alt_0 || ORIG_REF_NAME==zynq7010_fb0_use_alt_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/zynq7010_zynq7010_axi4_fbread_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_zynq7010_axi4_fbread_0_0 || ORIG_REF_NAME==zynq7010_zynq7010_axi4_fbread_0_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_inverter_0_0/zynq7010_inverter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_inverter_0_0 || ORIG_REF_NAME==zynq7010_inverter_0_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_render_2d_0_1/zynq7010_render_2d_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_render_2d_0_1 || ORIG_REF_NAME==zynq7010_render_2d_0_1} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_auto_pc_0/zynq7010_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_auto_pc_0 || ORIG_REF_NAME==zynq7010_auto_pc_0} -quiet] -quiet

# IP: bd/zynq7010/ip/zynq7010_auto_pc_1/zynq7010_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7010_auto_pc_1 || ORIG_REF_NAME==zynq7010_auto_pc_1} -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/zynq7010_ooc.xdc
