# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.srcs/sources_1/bd/zynq7010/ip/zynq7010_render_2d_0_1/zynq7010_render_2d_0_1.xci
# IP: The module: 'zynq7010_render_2d_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_render_2d_0_1/constraints/render_2d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7010_render_2d_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.srcs/sources_1/bd/zynq7010/ip/zynq7010_render_2d_0_1/zynq7010_render_2d_0_1.xci
# IP: The module: 'zynq7010_render_2d_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_render_2d_0_1/constraints/render_2d_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7010_render_2d_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
