# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.srcs/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/zynq7010_zynq7010_axi4_fbread_0_0.xci
# IP: The module: 'zynq7010_zynq7010_axi4_fbread_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/event_fifo_1/event_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==event_fifo || ORIG_REF_NAME==event_fifo} -quiet] -quiet

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/channel_fifo_1/channel_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==channel_fifo || ORIG_REF_NAME==channel_fifo} -quiet] -quiet

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/event_fifo_1/event_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==event_fifo || ORIG_REF_NAME==event_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/channel_fifo_1/channel_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==channel_fifo || ORIG_REF_NAME==channel_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.srcs/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/zynq7010_zynq7010_axi4_fbread_0_0.xci
# IP: The module: 'zynq7010_zynq7010_axi4_fbread_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/event_fifo_1/event_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==event_fifo || ORIG_REF_NAME==event_fifo} -quiet] -quiet

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/channel_fifo_1/channel_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==channel_fifo || ORIG_REF_NAME==channel_fifo} -quiet] -quiet

# IP: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0_ooc.xdc

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/event_fifo_1/event_fifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==event_fifo || ORIG_REF_NAME==event_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/channel_fifo_1/channel_fifo.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==channel_fifo || ORIG_REF_NAME==channel_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc
