#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : zynq7010.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Dec 17 15:18:20 CST 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: zynq7010.sh [-help]
# usage: zynq7010.sh [-lib_map_path]
# usage: zynq7010.sh [-noclean_files]
# usage: zynq7010.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'zynq7010.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_13 processing_system7_vip_v1_0_15 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xlslice_v1_0_2 xlconcat_v2_1_4 fifo_generator_v13_2_7 blk_mem_gen_v8_4_5 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_26 axi_register_slice_v2_1_27 axi_protocol_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "zynq7010.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_15 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_processing_system7_0_0/sim/zynq7010_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_proc_sys_reset_0_0/sim/zynq7010_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_xlslice_0_0/sim/zynq7010_xlslice_0_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_audio_shift_1/sim/zynq7010_audio_shift_1.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_audio_en_0/sim/zynq7010_audio_en_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_audio_type_0/sim/zynq7010_audio_type_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_fb_use_alt_0/sim/zynq7010_fb_use_alt_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_fb_use_alt1_0/sim/zynq7010_fb_use_alt1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_xlconcat_0_1/sim/zynq7010_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_xlconcat_1_0/sim/zynq7010_xlconcat_1_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_fb0_use_alt_0/sim/zynq7010_fb0_use_alt_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1/clk_wiz_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/event_fifo_1/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/event_fifo_1/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/event_fifo_1/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/event_fifo_1/sim/event_fifo.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/channel_fifo_1/sim/channel_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/blk_mem_gen_0_1/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/blk_mem_gen_0_1/sim/blk_mem_gen_0.v" \
    "$ref_dir/../../../bd/zynq7010/ipshared/17c3/hdl/encode.v" \
    "$ref_dir/../../../bd/zynq7010/ipshared/17c3/hdl/hdmi_tx_v1_0.v" \
    "$ref_dir/../../../bd/zynq7010/ipshared/17c3/hdl/serdes_10_to_1.v" \
    "$ref_dir/../../../bd/zynq7010/ipshared/17c3/hdl/srldelay.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq7010/ipshared/17c3/hdl/VGA_controller.sv" \
    "$ref_dir/../../../bd/zynq7010/ipshared/17c3/hdl/axi4_fbreader_to_hdmi_v1_0_M00_AXI.sv" \
    "$ref_dir/../../../bd/zynq7010/ipshared/17c3/hdl/pwm_driver.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq7010/ipshared/17c3/hdl/axi4_fbreader_to_hdmi_v1_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/sim/zynq7010_zynq7010_axi4_fbread_0_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_inverter_0_0/sim/zynq7010_inverter_0_0.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_bucket_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_bullet_sprite_V_RAM_1WNR_AUTO_1R1W.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_enemy_bullet_V_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_flow_control_loop_pipe_sequential_init.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_grid_info_enemy_bullets_V_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_grid_info_player_bullets_V_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_mux_164_32_1_1.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_player_bullet_V_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_render_2d_Pipeline_clear_tile_y_clear_tile_x.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_render_2d_Pipeline_render_enemy_bullets_render_enemy_bullets_x.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_render_2d_Pipeline_render_player_bullets_render_player_bullets_x.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_tile_fb_V_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d_vram_m_axi.v" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/046e/hdl/verilog/render_2d.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_render_2d_0_1/sim/zynq7010_render_2d_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../ZYNQ7010_2022.gen/sources_1/bd/zynq7010/ip/zynq7010_zynq7010_axi4_fbread_0_0/src/clk_wiz_0_1" +incdir+"/home/ztn/Embedded/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_auto_pc_0/sim/zynq7010_auto_pc_0.v" \
    "$ref_dir/../../../bd/zynq7010/ip/zynq7010_auto_pc_1/sim/zynq7010_auto_pc_1.v" \
    "$ref_dir/../../../bd/zynq7010/sim/zynq7010.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.zynq7010 xil_defaultlib.glbl -o zynq7010_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./zynq7010_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./zynq7010.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/ztn/Embedded/ZYNQ7010_2022/ZYNQ7010_2022.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key zynq7010_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc zynq7010_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./zynq7010.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: zynq7010.sh [-help]\n\
Usage: zynq7010.sh [-lib_map_path]\n\
Usage: zynq7010.sh [-reset_run]\n\
Usage: zynq7010.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
